project:
  type: website

website:
  title: "Bloguito"
  google-analytics: "G-YBQH55JB4K"
  page-navigation: true
  cookie-consent: true
  navbar:
    left:
      - about.qmd
      - talks.qmd
      - projects.qmd
      #- events.qmd
      - awards.qmd
    right:
      - icon: github
        href: https://github.com/itepifanio
      - icon: twitter
        href: https://twitter.com/itepifanio
      - icon: linkedin
        href: https://www.linkedin.com/in/italoepifanio
format:
  html:
    theme: 
      light: flatly
      #dark: darkly
    css: styles.css
    toc: true
    toc-location: left
