project:
  type: website

website:
  title: "Bloguito"
  navbar:
    left:
      - talks.qmd
      - projects.qmd
      - events.qmd
      - awards.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/itepifanio
      - icon: twitter
        href: https://twitter.com/itepifanio
      - icon: linkedin
        href: https://www.linkedin.com/in/italoepifanio
format:
  html:
    theme: flatly
    css: styles.css



