---
pagetitle: "Talks"
title: "Talks"
---

## Protegendo seu ambiente jupyter e mais um pouco - [10º Meetup GruPy RN Mossoró](https://blog.grupyrn.org/meetup-10-mossoro/)

02/12/2023

Essa palestra discute os elementos de segurança no ambiente de análise de dados, com foco 
na ferramenta Jupyter notebook e mais especificamente o seu servidor. Foi demonstrado a 
instalação e uso da ferramenta [Jupysec](https://github.com/JosephTLucas/jupysec) para 
exibir possiveis problemas de segurança no servidor.

## Usando Python e dados para desenvolver dashboards, interfaces e aplicações - [Nivercon](https://nivercon.com/)

07/10/2023

Você não precisa saber javascript para desenvolver interfaces reativas. Pessoas que 
trabalham com dados geralmente tem algum conhecimento em Python e isso é suficiente 
para desenvolver interfaces poderosas.

Essa palestra apresentou uma prova de conceito para construção da ferramenta 
[UFRN Cheat Sheet](https://github.com/itepifanio/ufrn-cheat-sheet/), explorando diversas 
ferramentas que usam Python para desenvolver interfaces. 
[Foram exploradas](https://github.com/itepifanio/usando-python-e-dados-para-desenvolver-dashboards) 
as bibliotecas ipywidgets com voilà, Dash, Solara e Streamlit. Por fim, Solara apresentou 
o melhor caso de uso dentre as ferramentas testadas, apresentando melhor reuso de código e 
controle de estado que as demais ferramentas.

## Indo além com Jupyter Notebooks: Desenvolva o seu primeiro pacote python com programação letrada - [Python Nordeste 2023](https://pretalx.com/python-nordeste-2023/talk/ZRHNW8/)

24/09/2023

Programação letrada é um paradigma de programação que incorpora explicações em 
linguagem natural (como espanhol) junto com código tradicional. Programação letrada 
permite que desenvolvedores contem uma história com seu código, melhorando o entendimento 
do projeto, focando com documentação e facilitando a integração de novos desenvolvedores.

Mesmo sendo um conceito respeitado e defendido por pesquisadores renomados, como Donald Knuth, 
ferramentas de programação letrada como Jupyter notebooks são considerados ineficientes para 
desenvolvimento de software. Essa percepção limitou a utilização de Jupyter notebooks a scripts 
simples e material educacional.

A biblioteca "Nbdev" demonstrou que programação letrada é útil para o desenvolvimento de grandes 
e sérios projetos, como FastAi.

Esse minicurso mostrou os benefícios de programação letrada ao mesmo tempo que utiliza das 
melhores práticas de desenvolvimento. Foi desenvolvido um pacote Python utilizando Jupyter Notebooks, 
além de publica-lo, realizar deploy de documentação, executar testes e CI/CD. Todo o material está 
[disponível aqui](https://github.com/itepifanio/indo-alem-com-jupyter-notebooks)

## Going beyond with Jupyter Notebooks: Write your first package using literate programming - [PyCon US 2023](https://us.pycon.org/2023/schedule/presentation/2/)

19/04/2023

Literate programming is a programming paradigm that incorporates explanations in natural language 
(such as Spanish) embedded with the traditional code. Literate programming allows developers to tell 
a story with their codes, improving the understanding of the project, focusing on documentation, and making
it easier to onboard developers. Although being a very well-regarded concept discussed by respected 
researchers like Donald Knuth, literate programming tools like Jupyter notebooks are considered inefficient 
for serious software development. This perception has limited Jupyter notebooks to simple python scripts 
and educational materials.

The Nbdev library has proven that literate programming is useful in developing big and serious projects, like FastAi. 
This tutorial will show attendees how to get the benefits of literate programming while also following software development 
best practices. We'll get hands-on experience in writing and publishing a Python Package while using Jupyter Notebooks. 
In addition to publishing the package, we'll also learn how to deploy the docs, run simple tests and run these tests on CI/CD, 
making sure that our package will only get published if the tests pass.

Even though this tutorial uses Jupyter Notebooks and Nbdev the student doesn't need previous knowledge of these tools. 
A simple computer with Python and pip installed is all we'll use. Students should have some minimal Python knowledge 
and Git experience (Simple commands like push, pull, add and commit). A GitHub account will also be necessary.

## Utilizando Ipyannotator para anotações de tráfego - [Python Nordeste 2022](https://2022.pythonnordeste.org/)

28/08/2022

Palestra sobre o uso do framework Ipyannotator, o qual fui mantenedor, para anotação de tráfego terrestre. 
A ferramenta foi utilizada como caso de uso do projeto City Count.
